// Seed Data strictly adhering to IPC Management Portal SRS v1.0 specifications
import {
  Hospital,
  User,
  Visit,
  AuditLog,
  TrainingTemplate,
  Training,
  Practitioner,
  Equipment,
  Policy,
  OrgDocument,
  DocumentCenterFile,
  Program,
  Notification
} from '../types/ipc';

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-1',
    name: 'مستشفى الملك فهد التخصصي',
    location: 'المنطقة الشرقية - الدمام',
    type: 'مرجعي تخصصي',
    coordinatorName: 'منسق مكافحة العدوى',
    coordinatorEmail: 'coordinator.kfsh@cluster.med.sa',
    isActive: true,
    createdAt: '2026-01-15T08:00:00.000Z',
  },
  {
    id: 'hosp-2',
    name: 'مستشفى النور التخصصي',
    location: 'منطقة مكة المكرمة - العاصمة المقدسة',
    type: 'تخصصي عام',
    coordinatorName: 'منسق مكافحة العدوى',
    coordinatorEmail: 'coordinator.alnoor@cluster.med.sa',
    isActive: true,
    createdAt: '2026-01-20T08:00:00.000Z',
  },
  {
    id: 'hosp-3',
    name: 'مستشفى الولادة والأطفال المركزي',
    location: 'منطقة الرياض - وسط الرياض',
    type: 'تخصصي نساء وأطفال',
    coordinatorName: 'منسق مكافحة العدوى',
    coordinatorEmail: 'coordinator.maternity@cluster.med.sa',
    isActive: true,
    createdAt: '2026-02-01T08:00:00.000Z',
  },
  {
    id: 'hosp-4',
    name: 'مستشفى الأمير سلطان بن عبدالعزيز',
    location: 'منطقة القصيم - بريدة',
    type: 'عام',
    coordinatorName: 'منسق مكافحة العدوى',
    coordinatorEmail: 'coordinator.psh@cluster.med.sa',
    isActive: true,
    createdAt: '2026-02-10T08:00:00.000Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-central-1',
    email: 'admin@ipc-cluster.gov.sa',
    name: 'مشرف الإدارة المركزية لمكافحة العدوى',
    role: 'central',
    hospitalId: null,
    password: 'admin123',
    createdAt: '2026-01-01T08:00:00.000Z',
  },
  {
    id: 'user-hosp-1',
    email: 'coordinator.kfsh@cluster.med.sa',
    name: 'منسق مستشفى الملك فهد التخصصي',
    role: 'hospital',
    hospitalId: 'hosp-1',
    password: '123456',
    phone: '0501112233',
    createdAt: '2026-01-15T09:00:00.000Z',
  },
  {
    id: 'user-hosp-2',
    email: 'coordinator.alnoor@cluster.med.sa',
    name: 'منسق مستشفى النور التخصصي',
    role: 'hospital',
    hospitalId: 'hosp-2',
    password: '123456',
    phone: '0502223344',
    createdAt: '2026-01-20T09:00:00.000Z',
  },
  {
    id: 'user-hosp-3',
    email: 'coordinator.maternity@cluster.med.sa',
    name: 'منسق مستشفى الولادة والأطفال',
    role: 'hospital',
    hospitalId: 'hosp-3',
    password: '123456',
    phone: '0503334455',
    createdAt: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'user-hosp-4',
    email: 'coordinator.psh@cluster.med.sa',
    name: 'منسق مستشفى الأمير سلطان',
    role: 'hospital',
    hospitalId: 'hosp-4',
    password: '123456',
    phone: '0504445566',
    createdAt: '2026-02-10T09:00:00.000Z',
  },
];

export const INITIAL_VISITS: Visit[] = [
  {
    id: 'visit-101',
    hospitalId: 'hosp-1',
    hospitalName: 'مستشفى الملك فهد التخصصي',
    visitDate: '2026-09-08T09:30:00.000Z',
    team: 'فريق الرقابة الإشرافية المركزي (استشاري وبائيات، أخصائي تمريض، فني تعقيم)',
    details: 'زيارة تدقيق شاملة على أقسام العناية المركزة (ICU)، وحدة الغسيل الكلوي، وقسم التعقيم المركزي (CSSD). لوحظ مستوى متقدم في غرف العزل بالضغط السالب مع توصية بمعايرة أجهزة قياس تدفق الهواء دورياً.',
    reportUrl: '/reports/visit-kfsh-sep2026.pdf',
    reportName: 'تقرير_زيارة_الملك_فهد_الربع_الثالث_2026.pdf',
    status: 'in_progress',
    complianceScore: 88,
    createdAt: '2026-09-08T14:00:00.000Z',
    updatedAt: '2026-09-10T11:20:00.000Z',
    attachments: [
      {
        id: 'att-1',
        visitId: 'visit-101',
        fileName: 'صورة_غرفة_العزل_ICU_12.jpg',
        fileUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
        uploadedAt: '2026-09-08T15:00:00.000Z',
      },
      {
        id: 'att-2',
        visitId: 'visit-101',
        fileName: 'سجل_فحص_جهاز_الأوتوكلاف_CSSD.jpg',
        fileUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
        uploadedAt: '2026-09-08T15:05:00.000Z',
      },
    ],
    responses: [
      {
        id: 'resp-1',
        visitId: 'visit-101',
        note: 'تم استلام تقرير الزيارة والتنسيق الفوري مع قسم الهندسة الطبية لإعادة معايرة حساسات الضغط السالب بوحدات العزل وتوفير شهادة المعايرة المحدثة.',
        attachmentUrl: '/responses/calibration-action-plan.pdf',
        attachmentName: 'خطة_تصحيح_معايرة_الضغط_السالب.pdf',
        respondentName: 'منسق مكافحة العدوى بمستشفى الملك فهد التخصصي',
        respondedAt: '2026-09-10T11:20:00.000Z',
      },
    ],
  },
  {
    id: 'visit-102',
    hospitalId: 'hosp-2',
    hospitalName: 'مستشفى النور التخصصي',
    visitDate: '2026-08-18T10:00:00.000Z',
    team: 'فريق الرقابة الميدانية والتفتيش الإكلينيكي بالمديرية',
    details: 'زيارة متابعة ميدانية لتقييم تطبيق الحزم الوقائية لمنع عدوى الدم المرتبطة بالقساطر الوريدية المركزية (CLABSI). تم التأكد من اكتمال النماذج وتدريب 95% من طاقم التمريض بنجاح.',
    reportUrl: '/reports/visit-alnoor-aug2026.pdf',
    reportName: 'تقرير_تقييم_حزم_CLABSI_مستشفى_النور.pdf',
    status: 'completed',
    complianceScore: 94,
    createdAt: '2026-08-18T14:30:00.000Z',
    updatedAt: '2026-08-25T16:00:00.000Z',
    attachments: [
      {
        id: 'att-3',
        visitId: 'visit-102',
        fileName: 'توثيق_عربة_القساطر_المركزية.jpg',
        fileUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
        uploadedAt: '2026-08-18T15:20:00.000Z',
      },
    ],
    responses: [
      {
        id: 'resp-2',
        visitId: 'visit-102',
        note: 'تم إرفاق إحصائية خلو القسم من أي حالة عدوى CLABSI خلال الـ 60 يوماً الماضية، وجاهزية المستشفى للاعتماد النهائي.',
        attachmentUrl: '/responses/alnoor-clabsi-zero-audit.pdf',
        attachmentName: 'إحصائية_الصفر_عدوى_CLABSI.pdf',
        respondentName: 'منسق مكافحة العدوى بمستشفى النور التخصصي',
        respondedAt: '2026-08-23T09:15:00.000Z',
      },
    ],
  },
  {
    id: 'visit-103',
    hospitalId: 'hosp-3',
    hospitalName: 'مستشفى الولادة والأطفال المركزي',
    visitDate: '2026-09-22T09:00:00.000Z',
    team: 'فريق الإدارة المركزية لمكافحة العدوى بالمنشآت',
    details: 'زيارة مجدولة لتفقد إجراءات مكافحة العدوى في وحدة حديثي الولادة (NICU) وغرف العمليات القيصرية والتأكد من مخزون المستلزمات الوقائية.',
    reportUrl: '',
    reportName: '',
    status: 'in_progress',
    complianceScore: 78,
    createdAt: '2026-09-11T12:00:00.000Z',
    updatedAt: '2026-09-11T12:00:00.000Z',
    attachments: [],
    responses: [],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    entityType: 'Visit',
    entityId: 'visit-101',
    action: 'إنشاء زيارة رقابية جديدة وتحديد الفريق الزائر',
    performedBy: 'مشرف الإدارة المركزية (central)',
    timestamp: '2026-09-08T14:00:00.000Z',
  },
  {
    id: 'audit-2',
    entityType: 'Visit',
    entityId: 'visit-101',
    action: 'رفع تقرير الزيارة وإرفاق صور التدقيق الميداني',
    performedBy: 'مشرف الإدارة المركزية (central)',
    timestamp: '2026-09-08T15:05:00.000Z',
  },
  {
    id: 'audit-3',
    entityType: 'Visit',
    entityId: 'visit-101',
    action: 'إضافة رد رسمي من المستشفى وإرفاق خطة المعايرة',
    performedBy: 'منسق مكافحة العدوى (hospital)',
    timestamp: '2026-09-10T11:20:00.000Z',
  },
  {
    id: 'audit-4',
    entityType: 'Visit',
    entityId: 'visit-102',
    action: 'اعتماد الزيارة ونقل حالتها إلى "مكتمل" وأرشفتها نهائياً',
    performedBy: 'مشرف الإدارة المركزية (central)',
    timestamp: '2026-08-25T16:00:00.000Z',
  },
  {
    id: 'audit-5',
    entityType: 'Training',
    entityId: 'train-tmpl-1',
    action: 'إنشاء قالب تدريبي مركزي وتوليد النسخ التلقائية لكل المستشفيات',
    performedBy: 'مشرف الإدارة المركزية (central)',
    timestamp: '2026-09-01T10:00:00.000Z',
  },
];

export const INITIAL_TRAINING_TEMPLATES: TrainingTemplate[] = [
  {
    id: 'tmpl-1',
    title: 'البرنامج الوطني لنظافة الأيدي ونزع القفازات Safe Hands 2026',
    description: 'تدريب تفاعلي إلزامي لكافة الكوادر الصحية على اللحظات الخمس لنظافة الأيدي التابعة لمنظمة الصحة العالمية، مع تطبيق عملي وفحص بالأشعة فوق البنفسجية.',
    dueDate: '2026-09-30T23:59:59.000Z',
    createdAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'tmpl-2',
    title: 'إدارة وتطهير الانسكابات الدموية والسوائل الحيوية',
    description: 'ورشة عمل متخصصة لطواقم التمريض والخدمات المساندة حول استخدام أطقم انسكابات الدم (Blood Spill Kits) وتطبيق محاليل الكلور بنسب التركيز الصحيحة.',
    dueDate: '2026-10-15T23:59:59.000Z',
    createdAt: '2026-09-05T11:30:00.000Z',
  },
];

export const INITIAL_TRAININGS: Training[] = [
  {
    id: 'train-1',
    templateId: 'tmpl-1',
    hospitalId: 'hosp-1',
    hospitalName: 'مستشفى الملك فهد التخصصي',
    title: 'البرنامج الوطني لنظافة الأيدي ونزع القفازات Safe Hands 2026',
    description: 'تدريب تفاعلي إلزامي لكافة الكوادر الصحية على اللحظات الخمس لنظافة الأيدي التابعة لمنظمة الصحة العالمية.',
    deliveredBy: 'فريق التدريب والتعليم المستمر بمكافحة العدوى',
    date: '2026-09-09T10:00:00.000Z',
    status: 'completed',
    createdAt: '2026-09-01T10:00:00.000Z',
    attendances: [
      { id: 'att-user-1', trainingId: 'train-1', practitionerId: 'prac-1', practitionerName: 'استشاري وبائيات ومكافحة عدوى' },
      { id: 'att-user-2', trainingId: 'train-1', practitionerId: 'prac-2', practitionerName: 'أخصائي أول مكافحة عدوى' },
      { id: 'att-user-3', trainingId: 'train-1', practitionerId: 'prac-3', practitionerName: 'أخصائية تمريض وضبط العدوى' },
      { id: 'att-user-4', trainingId: 'train-1', headcount: 42 },
    ],
    attachments: [
      {
        id: 't-att-1',
        trainingId: 'train-1',
        fileName: 'توثيق_جلسة_التدريب_العملية_قاعة_المؤتمرات.jpg',
        fileUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
        uploadedAt: '2026-09-09T13:00:00.000Z',
      },
    ],
  },
  {
    id: 'train-2',
    templateId: 'tmpl-1',
    hospitalId: 'hosp-2',
    hospitalName: 'مستشفى النور التخصصي',
    title: 'البرنامج الوطني لنظافة الأيدي ونزع القفازات Safe Hands 2026',
    description: 'تدريب تفاعلي إلزامي لكافة الكوادر الصحية على اللحظات الخمس لنظافة الأيدي التابعة لمنظمة الصحة العالمية.',
    deliveredBy: 'فريق قسم مكافحة العدوى بمستشفى النور',
    date: null,
    status: 'pending',
    createdAt: '2026-09-01T10:00:00.000Z',
    attendances: [],
    attachments: [],
  },
  {
    id: 'train-3',
    templateId: 'tmpl-1',
    hospitalId: 'hosp-3',
    hospitalName: 'مستشفى الولادة والأطفال المركزي',
    title: 'البرنامج الوطني لنظافة الأيدي ونزع القفازات Safe Hands 2026',
    description: 'تدريب تفاعلي إلزامي لكافة الكوادر الصحية على اللحظات الخمس لنظافة الأيدي التابعة لمنظمة الصحة العالمية.',
    deliveredBy: '',
    date: null,
    status: 'late',
    createdAt: '2026-09-01T10:00:00.000Z',
    attendances: [],
    attachments: [],
  },
  {
    id: 'train-4',
    templateId: 'tmpl-1',
    hospitalId: 'hosp-4',
    hospitalName: 'مستشفى الأمير سلطان بن عبدالعزيز',
    title: 'البرنامج الوطني لنظافة الأيدي ونزع القفازات Safe Hands 2026',
    description: 'تدريب تفاعلي إلزامي لكافة الكوادر الصحية على اللحظات الخمس لنظافة الأيدي التابعة لمنظمة الصحة العالمية.',
    deliveredBy: 'منسق مكافحة العدوى والتدريب بالمستشفى',
    date: '2026-09-07T08:30:00.000Z',
    status: 'completed',
    createdAt: '2026-09-01T10:00:00.000Z',
    attendances: [
      { id: 'att-user-5', trainingId: 'train-4', headcount: 65 },
    ],
    attachments: [],
  },
  // FR-20: Independent internal hospital training
  {
    id: 'train-internal-1',
    templateId: null,
    hospitalId: 'hosp-1',
    hospitalName: 'مستشفى الملك فهد التخصصي',
    title: 'تدريب داخلي: إجراءات التعقيم والتطهير عالي المستوى لمناظير الجهاز الهضمي',
    description: 'تدريب داخلي لمنسوبي وحدة المناظير وأخصائيي التعقيم المركزي وفق المعايير المحدثة لوزارة الصحة.',
    deliveredBy: 'مشرف قسم التعقيم المركزي (CSSD)',
    date: '2026-09-04T11:00:00.000Z',
    status: 'completed',
    createdAt: '2026-09-03T09:00:00.000Z',
    attendances: [
      { id: 'att-int-1', trainingId: 'train-internal-1', practitionerId: 'prac-4', practitionerName: 'فني أول تعقيم مركزي (CSSD)' },
      { id: 'att-int-2', trainingId: 'train-internal-1', headcount: 14 },
    ],
    attachments: [
      {
        id: 't-att-2',
        trainingId: 'train-internal-1',
        fileName: 'شهادات_حضور_دورة_المناظير.pdf',
        fileUrl: '/docs/endoscope-training-certificates.pdf',
        uploadedAt: '2026-09-04T15:30:00.000Z',
      },
    ],
  },
];

export const INITIAL_PRACTITIONERS: Practitioner[] = [
  {
    id: 'prac-1',
    hospitalId: 'hosp-1',
    name: 'ممارس صحي - استشاري وبائيات',
    role: 'استشاري وبائيات ومكافحة عدوى',
    licenseNumber: 'SCHS-21-99882',
    contact: 'epidemiology.kfsh@cluster.med.sa',
  },
  {
    id: 'prac-2',
    hospitalId: 'hosp-1',
    name: 'ممارس صحي - أخصائي أول مكافحة عدوى',
    role: 'أخصائي أول مكافحة عدوى',
    licenseNumber: 'SCHS-19-44512',
    contact: 'ipc.specialist.kfsh@cluster.med.sa',
  },
  {
    id: 'prac-3',
    hospitalId: 'hosp-1',
    name: 'ممارس صحي - تمريض ضبط عدوى ICU',
    role: 'أخصائية تمريض وضبط العدوى (ICU)',
    licenseNumber: 'SCHS-22-11309',
    contact: 'nursing.icu.kfsh@cluster.med.sa',
  },
  {
    id: 'prac-4',
    hospitalId: 'hosp-1',
    name: 'ممارس صحي - فني تعقيم مركزي CSSD',
    role: 'فني أول تعقيم مركزي (CSSD)',
    licenseNumber: 'SCHS-18-77631',
    contact: 'cssd.kfsh@cluster.med.sa',
  },
  {
    id: 'prac-5',
    hospitalId: 'hosp-2',
    name: 'ممارس صحي - استشاري أمراض معدية',
    role: 'استشاري أمراض معدية ومكافحة عدوى',
    licenseNumber: 'SCHS-17-33100',
    contact: 'id.specialist.alnoor@cluster.med.sa',
  },
];

export const INITIAL_EQUIPMENTS: Equipment[] = [
  {
    id: 'eq-1',
    hospitalId: 'hosp-1',
    name: 'جهاز تعقيم بالبخار عالي السعة Getinge GSS67',
    type: 'جهاز تعقيم بخاري (Autoclave)',
    serialNumber: 'GET-2024-88912',
    status: 'يعمل بكفاءة - تمت المعايرة',
  },
  {
    id: 'eq-2',
    hospitalId: 'hosp-1',
    name: 'نظام تطهير الغرف بالبخار الجاف Hydrogen Peroxide Bioquell BQ-50',
    type: 'جهاز تطهير بيئي بالرذاذ',
    serialNumber: 'BQ-2023-412',
    status: 'يعمل بكفاءة',
  },
  {
    id: 'eq-3',
    hospitalId: 'hosp-1',
    name: 'كابينة أمان حيوي Class II Type A2 Biosafety Cabinet',
    type: 'كبائن السلامة البيولوجية',
    serialNumber: 'BSC-2022-901',
    status: 'جاهز للاستخدام',
  },
  {
    id: 'eq-4',
    hospitalId: 'hosp-1',
    name: 'جهاز مراقبة وتتبع نظافة الأسطح Hygiena Ensure Touch ATP',
    type: 'جهاز فحص ونظافة الأسطح',
    serialNumber: 'HYG-ATP-2025',
    status: 'يعمل بكفاءة',
  },
  {
    id: 'eq-5',
    hospitalId: 'hosp-2',
    name: 'معقم بلازما درجات حرارة منخفضة Sterrad 100NX',
    type: 'معقم بلازما غاز الهيدروجين',
    serialNumber: 'ASP-100NX-6612',
    status: 'يعمل بكفاءة',
  },
];

export const INITIAL_POLICIES: Policy[] = [
  {
    id: 'pol-1',
    title: 'سياسة العزل الصحي للمرضى المصابين بميكروبات شديدة المقاومة (MDRO Policy)',
    category: 'policy',
    fileUrl: '/policies/mdro-isolation-policy-2026.pdf',
    fileName: 'سياسة_عزل_الميكروبات_المقاومة_MDRO_2026.pdf',
    version: '2.3',
    uploadedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'pol-2',
    title: 'إجراءات العمل القياسية (SOP) لتطهير مناظير الجهاز الهضمي والقصبي المرنة',
    category: 'procedure',
    fileUrl: '/policies/sop-endoscope-reprocessing.pdf',
    fileName: 'إجراءات_تطهير_المناظير_المرنة_SOP.pdf',
    version: '3.1',
    uploadedAt: '2026-08-15T11:00:00.000Z',
  },
  {
    id: 'pol-3',
    title: 'نموذج التقصي الوبائي الميداني لتفشي العدوى داخل المنشأة (Outbreak Investigation)',
    category: 'form',
    fileUrl: '/policies/outbreak-investigation-form.pdf',
    fileName: 'نموذج_التقصي_الوبائي_عالي_الخطورة.pdf',
    version: '1.4',
    uploadedAt: '2026-08-20T12:00:00.000Z',
  },
  {
    id: 'pol-4',
    title: 'سياسة الحزم الوقائية لمنع عدوى مجرى الدم المرتبطة بالقساطر المركزية (CLABSI Bundle)',
    category: 'policy',
    fileUrl: '/policies/clabsi-prevention-bundle.pdf',
    fileName: 'سياسة_حزم_الوقاية_CLABSI_المحدثة.pdf',
    version: '2.0',
    uploadedAt: '2026-09-01T09:00:00.000Z',
  },
];

export const INITIAL_ORG_DOCUMENTS: OrgDocument[] = [
  {
    id: 'org-1',
    title: 'الهيكل التنظيمي المعتمد للإدارة المركزية لمكافحة العدوى بالتجمع الصحي',
    type: 'org_structure',
    fileUrl: '/org/ipc-cluster-org-chart-2026.pdf',
    fileName: 'الهيكل_التنظيمي_المعتمد_مكافحة_العدوى_2026.pdf',
    uploadedAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'org-2',
    title: 'الوصف الوظيفي المعتمد لمنسق مكافحة العدوى بالمستشفى والمنشآت الصحية',
    type: 'job_description',
    fileUrl: '/org/ipc-hospital-coordinator-job-desc.pdf',
    fileName: 'بطاقة_الوصف_الوظيفي_منسق_مكافحة_العدوى.pdf',
    uploadedAt: '2026-01-12T11:00:00.000Z',
  },
];

export const INITIAL_DOCUMENT_CENTER: DocumentCenterFile[] = [
  {
    id: 'doc-1',
    title: 'الدليل الوطني الإرشادي الموحد لمكافحة العدوى بالمملكة العربية السعودية (الإصدار الخامس)',
    fileUrl: '/docs/saudi-national-ipc-guidelines-v5.pdf',
    fileName: 'الدليل_الوطني_لمكافحة_العدوى_v5.pdf',
    category: 'أدلة إرشادية وطنية',
    uploadedAt: '2026-02-01T10:00:00.000Z',
  },
  {
    id: 'doc-2',
    title: 'تعميم معايير تحصين الكوادر الصحية ضد الإنفلونزا الموسمية والالتهاب الكبدي الوبائي',
    fileUrl: '/docs/healthcare-worker-immunization-circular.pdf',
    fileName: 'تعميم_تحصين_الكوادر_الصحية_2026.pdf',
    category: 'تعاميم ولوائح',
    uploadedAt: '2026-08-28T09:00:00.000Z',
  },
  {
    id: 'doc-3',
    title: 'معايير سباهي (CBAHI) المحدثة لمكافحة العدوى والتعقيم المركزي',
    fileUrl: '/docs/cbahi-ipc-standards-latest.pdf',
    fileName: 'معايير_سباهي_CBAHI_مكافحة_العدوى.pdf',
    category: 'معايير الاعتماد والجودة',
    uploadedAt: '2026-07-15T14:00:00.000Z',
  },
  {
    id: 'doc-4',
    title: 'وثيقة المواصفات الفنية المعتمدة للمنصة الرقمية ودليل الصلاحيات (Official Specification & System Manual)',
    fileUrl: '/docs/OFFICIAL_SYSTEM_SPECIFICATIONS.md',
    fileName: 'وثيقة_المواصفات_الفنية_المعتمدة_للمنصة.pdf',
    category: 'التوثيق الفني والنظام',
    uploadedAt: '2026-09-15T12:00:00.000Z',
  },
];

export const INITIAL_PROGRAMS: Program[] = [
  {
    id: 'prog-1',
    name: 'البرنامج الوطني لسلامة ونظافة الأيدي (Clean Hands Protect Lives)',
    description: 'برنامج استراتيجي يهدف لرفع نسبة امتثال الكوادر الصحية لنظافة الأيدي إلى أعلى من 90% في كافة المستشفيات التابعة للتجمع.',
    createdAt: '2026-02-01T10:00:00.000Z',
    folders: [
      {
        id: 'fld-1',
        programId: 'prog-1',
        name: 'الأدلة والحقائب التدريبية',
        parentFolderId: null,
      },
      {
        id: 'fld-2',
        programId: 'prog-1',
        name: 'الملصقات التوعوية والمواد المرئية',
        parentFolderId: null,
      },
      {
        id: 'fld-3',
        programId: 'prog-1',
        name: 'استمارات الرصد وتدقيق الامتثال الدوري',
        parentFolderId: null,
      },
    ],
    files: [
      {
        id: 'pfile-1',
        programId: 'prog-1',
        folderId: 'fld-1',
        name: 'حقيبة_المدرب_المعتمد_لنظافة_الأيدي.pdf',
        fileUrl: '/programs/hand-hygiene/trainer-kit.pdf',
        fileSize: '4.2 MB',
        createdAt: '2026-02-05T11:00:00.000Z',
      },
      {
        id: 'pfile-2',
        programId: 'prog-1',
        folderId: 'fld-2',
        name: 'بوستر_اللحظات_الخمس_بالعربية_A3.pdf',
        fileUrl: '/programs/hand-hygiene/5-moments-poster.pdf',
        fileSize: '1.8 MB',
        createdAt: '2026-02-06T12:00:00.000Z',
      },
      {
        id: 'pfile-3',
        programId: 'prog-1',
        folderId: 'fld-3',
        name: 'نموذج_رصد_امتثال_الأيدي_الشهري.xlsx',
        fileUrl: '/programs/hand-hygiene/audit-tool.xlsx',
        fileSize: '650 KB',
        createdAt: '2026-02-10T14:00:00.000Z',
      },
      {
        id: 'pfile-root',
        programId: 'prog-1',
        folderId: null,
        name: 'الميثاق_الاستراتيجي_لبرنامج_نظافة_الأيدي_2026.pdf',
        fileUrl: '/programs/hand-hygiene/charter.pdf',
        fileSize: '2.1 MB',
        createdAt: '2026-02-01T10:30:00.000Z',
      },
    ],
  },
  {
    id: 'prog-2',
    name: 'برنامج ترصد عدوى المنشآت الصحية (Healthcare-Associated Infections - HAIs)',
    description: 'متابعة وترصد حالات العدوى المكتسبة (CLABSI, CAUTI, VAP, SSI) واستخلاص المؤشرات الوبائية لدعم اتخاذ القرار الوقائي.',
    createdAt: '2026-03-01T09:00:00.000Z',
    folders: [
      {
        id: 'fld-201',
        programId: 'prog-2',
        name: 'بروتوكولات ترصد عدوى مجرى الدم (CLABSI)',
        parentFolderId: null,
      },
      {
        id: 'fld-202',
        programId: 'prog-2',
        name: 'بروتوكولات ترصد عدوى المسالك البولية (CAUTI)',
        parentFolderId: null,
      },
      {
        id: 'fld-203',
        programId: 'prog-2',
        name: 'بروتوكولات ترصد عدوى الجروح الجراحية (SSI)',
        parentFolderId: null,
      },
    ],
    files: [
      {
        id: 'pfile-201',
        programId: 'prog-2',
        folderId: 'fld-201',
        name: 'دليل_حساب_معدل_CLABSI_لكل_1000_يوم_قسطرة.pdf',
        fileUrl: '/programs/hais/clabsi-rates-guide.pdf',
        fileSize: '3.1 MB',
        createdAt: '2026-03-05T10:00:00.000Z',
      },
      {
        id: 'pfile-202',
        programId: 'prog-2',
        folderId: null,
        name: 'الإطار_المرجعي_الموحد_لترصد_العدوى_المكتسبة.pdf',
        fileUrl: '/programs/hais/framework.pdf',
        fileSize: '5.4 MB',
        createdAt: '2026-03-01T11:00:00.000Z',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-hosp-3',
    type: 'training_overdue',
    message: 'تنبيه عاجل: تأخر تعبئة وتوثيق دورة "البرنامج الوطني لنظافة الأيدي" بمستشفى الولادة والأطفال عن الموعد المحدد.',
    isRead: false,
    createdAt: '2026-09-12T08:00:00.000Z',
    link: 'trainings',
  },
  {
    id: 'notif-2',
    userId: 'user-central-1',
    type: 'training_overdue',
    message: 'تنبيه نظام: يوجد تدريب متأخر عن الموعد بمستشفى الولادة والأطفال بحاجة لمتابعة مركزية.',
    isRead: false,
    createdAt: '2026-09-12T08:00:00.000Z',
    link: 'trainings',
  },
  {
    id: 'notif-3',
    userId: 'user-hosp-3',
    type: 'visit_upcoming',
    message: 'إشعار مجدول: اقتراب موعد الزيارة الرقابية الميدانية المقررة في 22 سبتمبر 2026 لوحدة العناية الفائقة.',
    isRead: false,
    createdAt: '2026-09-13T09:00:00.000Z',
    link: 'visits',
  },
  {
    id: 'notif-4',
    userId: 'user-hosp-1',
    type: 'new_document',
    message: 'تم اعتماد ورفع سياسة جديدة: "سياسة الحزم الوقائية لمنع عدوى مجرى الدم CLABSI Bundle v2.0".',
    isRead: false,
    createdAt: '2026-09-01T09:30:00.000Z',
    link: 'policies',
  },
];
